### ISSUE TITLE
Query execution event should be centralized

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-maps#13]
Currently, query execution happens within sensor (local) components, actuator (possibly global) components  and in Query Builder. 

We would like to have a centralized query executer so that all globally relevant queries are executed from a single place like QueryBuilder middleware.

Benefits:  
a. actuators can subscribe to the result events and result update events (of the query),  
b. this helps us minimize the websockets footprint and avoiding duplicate network requests.

We would still keep a component specific query executor for locally relevant results (example: showing aggregation on facets, showing full-text search results)

**Comment by siddharthlatest** [comment]
Update: Query execution is now actuator (class) specific. Here's how it works:

1. An actuator defines sensor dependencies which form the underlying query.  
2. Multiple actuators with the same query definition are grouped together (called a class) to form a single query connection.  

The end result is a DAG like dependency graph where multiple query connections might be open based on the number of actuator classes.

Is this correct @farhan687?

**Comment by farhan687** [comment]
Yes, correct but it is not class it is channel. 
Multiple actuators with the same query definition are grouped together (called a channel).

Channel contains then query input and on change of any sensor value it will execute query and invoke result in that channel.
