### ISSUE TITLE
Structuring of the main.js file

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-maps#17]
Use best practices:
* Mappings should be a separate namespace inside the ``state``. (useful when we introduce the mappings module later)  
* More intuitive event names (index, update, select)

**Comment by siddharthlatest** [comment]
@farhan687 what are we doing here?

**Comment by farhan687** [comment]
We are using props instead of state. and yes separate namespace inside props.
- Events name - `markerOnIndex`, `markerOnDelete`, `markerOnClick`, `markerOnDblclick`, `markerOnMouseover`, `markerOnMouseout`
