### ISSUE TITLE
Marker Popover Issues

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-maps#20]
- [x] Popover close action should not reposition the map center
- [x] Popover image not found should show a no pic (fixed size) and not this ![](https://i.imgur.com/sCn2eE1.png)  
- [ ] Some marker clicks reposition the map when opening a popover

**Comment by farhan687** [comment]
Fixed in dev: 15016a32870fed68c0650b8a7614f9068bebcc44 735d19c4a3b7e8ce49b2763614bf43ab5c0544aa

**Comment by siddharthlatest** [comment]
@farhan687 do you see the marker click reposition issue?

**Comment by siddharthlatest** [comment]
Google Map's default behavior is to reposition when a popover is opened to have it within the view. Will keep this behavior.
